### ISSUE TITLE
Train, Val, Test split

### ISSUE THREAD

**Issue by harishrithish7** [chenyilun95/DSGN#10]
Hi, 

Could you please let me know what is the train, val, test split used here?

Is it the same as https://xiaozhichen.github.io/files/mv3d/imagesets.tar.gz?

Thanks in advance.

**Comment by chenyilun95** [comment]
Yes, I think that's right. You can check the images number in the paper with the split you used.

**Comment by harishrithish7** [comment]
source: https://xiaozhichen.github.io/files/mv3d/imagesets.tar.gz
Train: 3711
Val: 3768

Paper:
Train: 3712
Val: 3769

There is a difference of 1 for both train and val. Could this cause any issue?

**Comment by chenyilun95** [comment]
I just opened the tar file you provided and it shows the number of images is exactly 3712. Could you check it again?

**Comment by harishrithish7** [comment]
Rechecked now and it matches. Thank you.
