### ISSUE TITLE
同一个目标多个预测框

### ISSUE THREAD

**Issue by yuguangs** [chenyilun95/DSGN#12]
您好，我使用finetune_53测试000016.png得到了这样的结果，请问是正常的吗
![QQ浏览器截图20201216145002](https://user-images.githubusercontent.com/60913278/102314914-22a19f00-3f6b-11eb-9779-3143cf173907.png)
我在test_net.py中如下位置添加了绘制包围框的代码，请问是在nms步骤之前进行了绘制吗？
![QQ浏览器截图20201216145113](https://user-images.githubusercontent.com/60913278/102315055-5ed4ff80-3f6b-11eb-8134-0f21d4c628d3.png)

**Comment by chenyilun95** [comment]
这是在NMS之后画框。可视化主要调score_thresh和nms_thresh，远处的物体可能确实预测准确比较难，你可以多看几张图。另外你可以稍微把NMS_THRESH调大一些，减少FP。另外在点云上做可视化应该可视化效果好一些，比较容易发现问题。

**Comment by yuguangs** [comment]
好的，我会多看几张图。请问score_thresh和nms_thresh在哪个文件当中呢？

**Comment by chenyilun95** [comment]
在对应model的config里面，
cfg.RPN3D.NMS_THRESH
cfg.RPN3D.POST_NMS_TOP_N （这里是top_N个框会被画出来）
你可以快速调一下这两个值。

**Comment by yuguangs** [comment]
在修改参数之后解决了这个问题。另外还想请教您，我在测试000032这张图片时的结果是这样的，
![QQ浏览器截图20201216180611](https://user-images.githubusercontent.com/60913278/102334249-5c33d380-3f86-11eb-99c4-c93216b6bf3d.png)
与您在sample_result中给出的例子不同，请问这可能是什么原因造成的呢？

**Comment by yuguangs** [comment]
请问您代码中是否有可视化的程序，我好像没有找到。

**Comment by chenyilun95** [comment]
是的 这里还没有可视化程序。你需要的话可以先试试这个代码 https://github.com/kuixu/kitti_object_vis 可以直接从output.txt去可视化。

**Comment by chenyilun95** [comment]
上面这个图你如果是说中间那辆车没有检测出来，你可以调一下score_thresh应该能出来。另外需要注意的确实会出现某些帧的检测缺失的情况也是正常的，可能是训练数据比较少或者data augmentation做得不充分导致的，你可以仔细去看下video demo每一帧对比下。还有就是训练的范围是在40m以内，40m以外的车是肯定检测不到的。

**Comment by yuguangs** [comment]
好的 多谢

**Comment by xiaozhihao0** [comment]
您好，请问目前项目有可视化的代码吗？
