### ISSUE TITLE
the error of the depth estimation

### ISSUE THREAD

**Issue by fangyixiao18** [chenyilun95/DSGN#13]
Hi, I have a question about the error of the depth estimation. Did you compute this error with different distance? For example, output the **mean** and **median** error in several distance bins, like 0-10m, 10-20m, 20-30m, 30-40m.

**Comment by chenyilun95** [comment]
Table 4 shows the mean and median depth error. Fig.5 in the supplementary part shows the detection accuracy vs. distance.  I think they should have similar trends. I remember pseudo-LiDAR++ has visualized depth errors vs. distances.

**Comment by fangyixiao18** [comment]
thank you very much! I'll check it.
