### ISSUE TITLE
tensorflow / tensorflow lite

### ISSUE THREAD

**Issue by rodrigoGA** [chenyilun95/DSGN#19]
First I want to congratulate you for the work done.
I would like to know if you plan to make a version that runs with tensorflow / tensorflow lite?

**Comment by chenyilun95** [comment]
Hi, I do not have a plan to make a tf version. But I am working on reformulating this repo to a modular and readable code.

**Comment by rodrigoGA** [comment]
Thanks. I will be aware of your repository.
I am interested in testing it on an edge device.
