### ISSUE TITLE
What time is the code available

### ISSUE THREAD

**Issue by SPengLiang** [chenyilun95/DSGN#2]
Hello, thanks for your great work!  I wanna know when is the code available

**Comment by chenyilun95** [comment]
Currently, I am still busy with other stuff and it takes some time to clean up the code. I hope I can release the full code in March.

**Comment by ofirkris** [comment]
Thanks, looking forward to testing it.

**Comment by tomshalini** [comment]
Thanks. I hope code will be available soon. Please confirm whether its in tensorflow or pytorch?

**Comment by chenyilun95** [comment]
Pytorch. 

I currently do not have the GPUs of enough memory and there was something wrong with the previous pre-trained models. So I need some time to fix them. I will release the code as soon as possible.

**Comment by chenyilun95** [comment]
Please check the code. Thanks!
