### ISSUE TITLE
About the construction of Plane Sweep Volume

### ISSUE THREAD

**Issue by Baboom-l** [chenyilun95/DSGN#20]
Hi！I wonder whether the camera parameters need to be introduced when building the Plane Sweep Volume. What is the difference between your Plane Sweep Volume and the Cost Volume in Stereo matching?

**Comment by chenyilun95** [comment]
I think you want to detail the difference between PSV and traditional stereo cost volume. PSV projects images to a set of equally-spaced depth planes while traditional cost volume projects images to a set of equally-spaced disparity planes (in stereo matching, it moves the right images pixel by pixel along the planes). Here, depth is inversely related to the disparity. You might check DSGN paper for details.

**Comment by Baboom-l** [comment]
Thank you for your reply. According to your paper, the features extracted from the right image when constructing the PSV is sub-pixel level. May I ask what strategy you adopted to extract the features corresponding to the depth of the right image?

**Comment by chenyilun95** [comment]
Given the float coordinate, features are extracted using bilinear interpolation. You may check https://github.com/dvlab-research/DSGN/blob/ac693e748ff3a7372b1292c2b7b3796854072030/dsgn/csrc/cuda/BuildCostVolume_cuda.cu#L86.

**Comment by Baboom-l** [comment]
Thanks a lot!
