### ISSUE TITLE
Question about setup(performance issue)

### ISSUE THREAD

**Issue by Ho1guma** [chenyilun95/DSGN#25]
I was so impressived by your model. Thank you for sharing! 
So I want to implement your model in my setup. But there are some issue in performance. 
I think it caused by pytorch version as you said in Troubleshooting.

At first my environment is as follows.

cuda 11.8
python 3.7
torch 1.8.0
torchvision 0.9.0
4 RTX 3090(24G) for training.

My train&test code is as follows

`python3 tools/train_net.py --cfg ./configs/default/config_car.py --savemodel ./outputs/dsgn_origin_4 -btrain 4 -d 0-3 --multiprocessing-distributed`
`python3 tools/test_net.py --loadmodel ./outputs/dsgn_origin_4/finetune_53.tar -btest 8 -d 0-3`

And my results
![image](https://github.com/dvlab-research/DSGN/assets/66930370/7a2bfbf2-1649-463b-9eeb-cdb63ab46401)
![image](https://github.com/dvlab-research/DSGN/assets/66930370/9ae6673e-7f67-44f3-84f7-dc4408beafe4)

Thank you for reading my issue.  Is there a problem with my setup?

**Comment by chenyilun95** [comment]
Can you get the same performance using the provided checkpoint? You might also check out [DSGN++](https://github.com/chenyilun95/DSGN2) that gets much better performance.

**Comment by Ho1guma** [comment]
Thank you for your replying. 
I experimented it using pretrained model that you uploaded to google drive.(DSGN_car_pretrained)

And the results are lower than before.

`python3 tools/test_net.py --loadmodel ./outputs/DSGN_car_pretrained/finetune_53.tar -btest 8 -d 0-3`
![image](https://github.com/dvlab-research/DSGN/assets/66930370/79ab8499-9ffb-4f7e-ad13-ce60a3c7677a)

By the way I saw this warning message, it can effect to the results? 
` UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")`
 `UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  "Default grid_sample and affine_grid behavior has changed "`
