### ISSUE TITLE
Test on waymo opendataset

### ISSUE THREAD

**Issue by bhack** [chenyilun95/DSGN#3]
Do you you have benchmarked this on Waymo open dataset? I would be really useful to compare on that dataset like RetinaTrack https://arxiv.org/abs/2003.13870

**Comment by chenyilun95** [comment]
As far as I know, Waymo dataset does not provide the stereo image pair data. Their cameras are of different directions, please refer https://waymo.com/open/data/.

**Comment by bhack** [comment]
Yes probably from figure n.1  in https://arxiv.org/pdf/1912.04838.pdf there are not valid stereo pairs in the front cameras field of view.
