### ISSUE TITLE
about run time

### ISSUE THREAD

**Issue by Jinyong-Huang** [chenyilun95/DSGN#4]
How long does it take to run a frame.

**Comment by zwqnju** [comment]
Referenced from his paper:
"On a NVIDIA Tesla V100 GPU, the inference time of DSGN for one image pair is 0.682s on average, where 2D feature extraction for left and right images takes 0.113s, constructing the plane-sweep volume and 3D geometric volume takes 0.285s, and 3D object detection on 3D geometric volume takes 0.284s.  The computation bottleneck of DSGN lies on 3D convolution layers."

**Comment by Jinyong-Huang** [comment]
thanks, I just saw it.
