### ISSUE TITLE
RuntimeError: cuda runtime error (209) : no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by tomshalini** [chenyilun95/DSGN#5]
I followed the same instruction as mentoned in README file but getting below error while running test_net.py

command : python3 tools/test_net.py --loadmodel ./outputs/DSGN_car_pretrained/ -btest 4 -d 2-3

Error: RuntimeError: cuda runtime error (209) : no kernel image is available for execution on the device

Environment Details:
Ubuntu 18.04
torch           1.3.0               
torchvision     0.4.1 
4GPU           GeForce RTX 2080  11GB

![CudaError_DSGN](https://user-images.githubusercontent.com/59674741/81756612-84bd9180-94bc-11ea-82fc-e5e0d68114ce.png)

**Comment by chenyilun95** [comment]
Did you build and compile the costvolume kernel successfully? It seems that it cannot find the compiled kernel.

**Comment by tomshalini** [comment]
As mentioned in README file i ran setup.py file successfully. Do i need to compile costvolume separately? Is the same mentioned in README file? If not how should i compile that?

[1]+  Done                    cd dsgn/utils/rotate_iou && bash compile.sh

Result of python3 setup.py build develop --user:

running build
running build_py
running build_ext
running develop
running egg_info
writing dsgn.egg-info/PKG-INFO
writing dependency_links to dsgn.egg-info/dependency_links.txt
writing top-level names to dsgn.egg-info/top_level.txt
reading manifest file 'dsgn.egg-info/SOURCES.txt'
writing manifest file 'dsgn.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.7/dsgn/_C.cpython-37m-x86_64-linux-gnu.so -> dsgn
Creating /home/shalini/.local/lib/python3.7/site-packages/dsgn.egg-link (link to .)
dsgn 0.1 is already the active version in easy-install.pth

Installed /home/shalini/Models/DSGN
Processing dependencies for dsgn==0.1
Finished processing dependencies for dsgn==0.1

**Comment by tomshalini** [comment]
> Did you build and compile the costvolume kernel successfully? It seems that it cannot find the compiled kernel.

As mentioned in README file i ran setup.py file successfully. Do i need to compile costvolume separately? Is the same mentioned in README file? If not how should i compile that?

[1]+ Done cd dsgn/utils/rotate_iou && bash compile.sh

Result of python3 setup.py build develop --user:

running build
running build_py
running build_ext
running develop
running egg_info
writing dsgn.egg-info/PKG-INFO
writing dependency_links to dsgn.egg-info/dependency_links.txt
writing top-level names to dsgn.egg-info/top_level.txt
reading manifest file 'dsgn.egg-info/SOURCES.txt'
writing manifest file 'dsgn.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.7/dsgn/_C.cpython-37m-x86_64-linux-gnu.so -> dsgn
Creating /home/shalini/.local/lib/python3.7/site-packages/dsgn.egg-link (link to .)
dsgn 0.1 is already the active version in easy-install.pth

Installed /home/shalini/Models/DSGN
Processing dependencies for dsgn==0.1
Finished processing dependencies for dsgn==0.1

**Comment by chenyilun95** [comment]
You do not have to compile the costvolume kernel separately. From your message, I think you should delete the build folder and rebuild it with python3 setup.py develop and see what happens. If it is successful, it will creates a .so file in dsgn/ folder.

**Comment by tomshalini** [comment]
> You do not have to compile the costvolume kernel separately. From your message, I think you should delete the build folder and rebuild it with python3 setup.py develop and see what happens. If it is successful, it will creates a .so file in dsgn/ folder.

Yes , it is resolved now.
Thank you so much for your time.

**Comment by chenyilun95** [comment]
That's great. :)
