### ISSUE TITLE
Using 3D Geometry Volume to predict depth.

### ISSUE THREAD

**Issue by ACkuku** [chenyilun95/DSGN#6]
Thanks for you work~. I have a question, if using 3D Geometry Volume to predict depth, like IMG->PSCV->3DV->Depth, the depth results is better? thanks.

**Comment by chenyilun95** [comment]
Hi, thanks for your interest! I did not get your point. Depth can be learned from PSCV for each image pixel in the frustum space. Or it can directly learn the voxelized point cloud in 3DV since it's in 3D world space.

**Comment by ACkuku** [comment]
sorry, I mean could using the 3D Geometry Volume to predict depth. As shown by the red arrow in the figure, instead of using plane sweep volume for depth prediction
![Fig2](https://user-images.githubusercontent.com/16281985/82450766-b26b9180-9adf-11ea-8402-a0cfac3b1cf0.png)

**Comment by chenyilun95** [comment]
3D Geometric Volume is constructed in (x,y,z) space and Plane Sweep Volume is constructed in (u,v,d) space. For the depth prediction, it generally means depth map (u,v), where each pixel stores the depth. So PSV is a more straightforward way to get the depth. What do you mean by using 3D Geometric Volume to predict the depth? Do you mean that project the 3D Geometric Volume back to (u,v,d) to get the depth?

**Comment by ACkuku** [comment]
Oh, I see. Thank you for your kind answer～
